# Generated by Django 5.1.3 on 2024-11-13 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_Empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('puesto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto_trabajo',
            fields=[
                ('id_puesto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_trabajo',
            fields=[
                ('id_historial', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('id_Empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clientes.empleado')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clientes.puesto_trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('id_Empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clientes.historial_trabajo')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clientes.puesto_trabajo')),
            ],
        ),
    ]
